{% set version = "3.0.17" %}

package:
    name: cint
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/libcint.git
    git_tag: devops/conda
requirements:
    build:
      - git
      - make
      - {{ compiler('c') }}			  
      - cmake {{ cmake }}
      - llvm-openmp			          # [osx]
      - intel-openmp
      - mkl-devel {{ mkl-devel }}
    host:
#      - pin_compatible('mkl')
      - python {{ python }}
    run:
      - pin_compatible('numpy')
test:
  commands:
    - test -f ${PREFIX}/lib/libcint$SHLIB_EXT
    - test -f ${PREFIX}/include/cint.h
    - ldd -r -u ${PREFIX}/lib/libcint$SHLIB_EXT # [linux]
    - ldd -v ${PREFIX}/lib/libcint$SHLIB_EXT    # [linux]
    - otool -L ${PREFIX}/lib/libcint$SHLIB_EXT  # [osx]
about:
    home: https://github.com/GQCG/libcint
    license: BSD 2-Clause "Simplified" License
    license_file: LICENSE
    summary: 'General GTO integrals for quantum chemistry.'
