{% set name = "cint" %}
{% set version = "3.0.17" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/libcint.git
    git_tag: develop
requirements:
    build:
      - git
      - make
      - {{ compiler('c') }}			  
      - cmake {{ cmake }}
      - mkl-static {{ mkl_static }}
      - mkl-include {{ mkl_include }}
    host:
      - python {{ python }}
      - {{ pin_compatible('numpy') }}
    run:
      - python {{ python }}
      - {{ pin_compatible('numpy') }}
test:
  commands:
    - test -f ${PREFIX}/lib/libcint$SHLIB_EXT
    - test -f ${PREFIX}/include/cint.h
    - ldd -v ${PREFIX}/lib/libcint$SHLIB_EXT    # [linux]
    - otool -L ${PREFIX}/lib/libcint$SHLIB_EXT  # [osx]
about:
    home: https://github.com/GQCG/libcint
    license: BSD
    license_file: LICENSE
    summary: 'General GTO integrals for quantum chemistry.'
