{% set version = "3.0.17" %}

package:
    name: cint
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/libcint.git
    git_tag: develop
requirements:
    build:
      - git
      - make
      - {{ compiler('c') }}			  
      - cmake {{ cmake }}
      - llvm-openmp			          # [osx]
      - intel-openmp
    host:
      - mkl-include {{ mkl_include }}
      - mkl-static {{ mkl_static }}
      - python
      - numpy
    run:
      - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
      - {{ pin_compatible('mkl-include', min_pin='x.x', max_pin='x.x') }}
      - {{ pin_compatible('mkl-static', min_pin='x.x', max_pin='x.x') }}
      - numpy
test:
  commands:
    - test -f ${PREFIX}/lib/libcint$SHLIB_EXT
    - test -f ${PREFIX}/include/cint.h
    - ldd -r -u ${PREFIX}/lib/libcint$SHLIB_EXT # [linux]
    - ldd -v ${PREFIX}/lib/libcint$SHLIB_EXT    # [linux]
    - otool -L ${PREFIX}/lib/libcint$SHLIB_EXT  # [osx]
    - conda inspect linkages --show-files --groupby=dependency $PKG_NAME
    - conda inspect objects -p ${PREFIX} $PKG_NAME # [osx]
about:
    home: https://github.com/GQCG/libcint
    license: BSD 2-Clause "Simplified" License
    license_file: LICENSE
    summary: 'General GTO integrals for quantum chemistry.'
