name: build

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8' 
      - uses: actions/checkout@v1
      - name: Download conda (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
      - name: Download conda (macOS)
        if: matrix.os == 'macos-latest'
        run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh
      - name: Install conda   
        run: |  
          bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
          echo "::add-path::$HOME/miniconda/bin"
      - name: Install conda dependencies 
        run: |
          conda install -c conda-forge cmake=3.13 blas=2.15 mkl=2019.0 eigen=3.3.7 numpy=1.18.1
          conda install -c intel mkl-static=2019.0 mkl-include=2019.0 intel-openmp=2019.0
      - name: Build, test and install
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=${HOME}/miniconda -DUSE_MKL=TRUE -DENABLE_TEST=1
          make -j3 && env CTEST_OUTPUT_ON_FAILURE=1 make test && sudo make install
